//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
Hi,

This is a small application to demonstrate the displaying of text in a highlighted form as it might be seen on social media such as Instagram.

In fact, the hashtags and the usernames that are entered here are ""live"" and can be used to navigate to an actual instagram hashtag. For example, some of the more popular hashtags are:

#cute 
#tbt
#follow.

In addition to hashtags, instagram user pages can be accessed through the user link, such as: @cszart, or @dubsteppickles.

Finally, email addresses, like admissions@zooatlanta.org, are also recognized; as well, as normal http links (http://www.google.com).

Thank you,

Chad Chandler ( chad.chandler@outlook.com )
")]
        public string InitalText {
            get {
                return ((string)(this["InitalText"]));
            }
            set {
                this["InitalText"] = value;
            }
        }
    }
}
